### ISSUE TITLE
cakebox with default to php7.2 now fails

### ISSUE THREAD

**Issue by dereuromark** [alt3/cakebox-console#125]
```
vagrant@cakebox:~$ cakebox
PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /cakebox/console/config/bootstrap.php:92
```

any cakebox command now doesnt work anymore.

**Comment by dereuromark** [comment]
turns out the /opt/composer composer.phar is outdated (Object PHp7.2 collision) and should be auto-provided/updated on vagrant init/reload etc.

Also missing then, ext-mbstring, ext-intl etc for php7.2.
sudo apt-get install php-mysql

**Comment by bravo-kernel** [comment]
At first glance something does indeed go wrong. A fresh box with standard yaml results in PHP7.2 and an error with the mysql extension (last screenshot).

![image](https://user-images.githubusercontent.com/230500/35886115-410918ea-0b90-11e8-89b8-1f4dd184d1d3.png)

![image](https://user-images.githubusercontent.com/230500/35886126-49246e76-0b90-11e8-8ce0-3e9afdb42fd5.png)

![image](https://user-images.githubusercontent.com/230500/35886184-7ba66638-0b90-11e8-9d83-ac8345a61787.png)

**Comment by bravo-kernel** [comment]
The core problem with the current upgrade is that PHP7.2 is installed while the extensions are hardcoded to 7.1 here https://github.com/alt3/cakebox/blob/dev/.cakebox/bash/ubuntu-16.sh#L115.

Starting https://github.com/alt3/cakebox/issues/91

**Comment by dereuromark** [comment]
I think we can always use `php-...` as it will auto-detect the right ones, then?
At least for my PHP7.2 box it worked to post-install them manually like this.

**Comment by bravo-kernel** [comment]
That's a neat trick I didn't know ❄️ 

However, I have added a PHP_VERSION variable that sets and replaces all references. If time permits I might make this into an option before executing the upgrade, giving user the choice between 7.1 and 7.2.

**Comment by bravo-kernel** [comment]
Closed through https://github.com/alt3/cakebox/issues/91

**Comment by bravo-kernel** [comment]
Permission fix found in last comment here https://github.com/alt3/cakebox/issues/91
