### ISSUE TITLE
Salt/cipher not unique

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox-console#57]
Cakebox Salt/cipher is currently hardcoded in the repo. Should:

- be generated during the initial installation, preferably as a composer post install command a-la CakePHP 3
- be integrated into Cakebox.yaml to support (re)creating box clones with matching salt/ciphers

**Comment by ceeram** [comment]
See also https://github.com/alt3/cakebox/issues/43

**Comment by ceeram** [comment]
This issue can be closed now, salt is now unique per installation. Only thing left is to be able to reuse the salt in backups. Another ticket has been opened for that
