### ISSUE TITLE
Do not show cakebox as application

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox-console#68]
Cakebox now appears in the list of "Applications" which is confusing.

+ show link to [Create your first website](http://cakebox.readthedocs.org/en/latest/tutorials/creating-your-first-website/) tutorial on Dashboard app-list if no apps are provisioned
+ update Virtual Hosts page as well (no need for the tutorial link, just an empty table a-la databases page)

@ceeram :bee:

**Comment by ceeram** [comment]
:P look who's assigned now

**Comment by ceeram** [comment]
I removed cakebox in list of applications, all thats left is to add a nice get started message

**Comment by bravo-kernel** [comment]
Fuck me, did you fix all this already too then :wink: 

https://github.com/alt3/cakebox-console/issues/68#ref-pullrequest-63444028

**Comment by ceeram** [comment]
i can fix the php notice, the donut and message i will leave up to you

2015-03-23 13:34 GMT+01:00 bravo-kernel <notifications@github.com>:

**Comment by bravo-kernel** [comment]
:+1:

**Comment by bravo-kernel** [comment]
Closing as https://github.com/alt3/cakebox-console/pull/91 is merged.
