### ISSUE TITLE
change composer version for debug kit

### ISSUE THREAD

**Issue by ceeram** [alt3/cakebox-console#77]
debugkit composer version should become ~3.0 when 3.0.1 is released, its pinned to dev-master atm to includes a fix to make php7 happy on travis

**Comment by ceeram** [comment]
3.0.1 had been released already

**Comment by bravo-kernel** [comment]
Feel free to make the PR

**Comment by ceeram** [comment]
thats why i assigned it to myself already ;)

**Comment by bravo-kernel** [comment]
Sorry, missed that, thanks :thumb:

**Comment by ceeram** [comment]
Closing, as there is PR open now
