### ISSUE TITLE
remove dev flag from composer install

### ISSUE THREAD

**Issue by ceeram** [alt3/cakebox-console#86]
cakephp/app no longer requires `-s dev` since it is now stable

https://github.com/alt3/cakebox-console/blob/9ba2a116260f1e35b549e95c9381b6fee8692db7/src/Lib/CakeboxExecute.php#L214

**Comment by bravo-kernel** [comment]
Would removing it also mean new projects are/can be created without dev (--no-dev)?

I originally used --no-dev intentionally to speed up the process significantly. Not sure if that's desired behavior though.

**Comment by ceeram** [comment]
--no-dev is about not including vendors that are only in required-dev, which is different from dev stability flag. -s dev is about allowing non-stable versions, which was needed before 3.0 stable.

**Comment by ceeram** [comment]
applications should not be installed with --no-dev flag, people need dev requirements in their applications ofcourse in this development box :)
