### ISSUE TITLE
Missing salt error

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/cakebox-console#92]
Given that the use of salt will be optional a missing ``config/salt.php`` should not cause a full stop preventing shells or dashboard from loading. Now produces these errors:
![missing-salt](https://cloud.githubusercontent.com/assets/230500/6809242/4fd7dcee-d259-11e4-83cb-c5f8cb6eab0f.png)

**Comment by ceeram** [comment]
salt is not optional, when installing it will be created, and as alreday
mentioned to recteate cakebox needs to get a new feature added

2015-03-24 19:12 GMT+01:00 bravo-kernel <notifications@github.com>:

**Comment by bravo-kernel** [comment]
I realized too late that this was only step 1 of many. Closing.
